
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author impROS
 */
public class frmAnaMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmAnaMenu
     */
    public frmAnaMenu() {
        initComponents();
    }
    ArrayList<String> arrNitelik = new ArrayList<>();
    ArrayList<String> arrTsag = new ArrayList<>();
    ArrayList<String> arrTsol = new ArrayList<>();
    ArrayList<Double> arrUygunlukDegeri = new ArrayList<>();
    String[][] arrTSolHesap;
    String[][] arrTSagHesap;
    String[][] arrVeriler;
    int satirSayisi, sutunSayisi;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtVeri = new javax.swing.JTextArea();
        btnOku = new javax.swing.JButton();
        txtSutunNo = new javax.swing.JTextField();
        btnSutunSil = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKonsol = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAdayBolunme = new javax.swing.JTextArea();
        btnAdayBol = new javax.swing.JButton();
        btnSolAgac = new javax.swing.JButton();
        btnSagAgac = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtSolAgac = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtSagAgac = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtUygunluk = new javax.swing.JTextArea();
        btnUygunlukDeger = new javax.swing.JButton();
        btnBol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtVeri.setColumns(20);
        txtVeri.setRows(5);
        txtVeri.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(153, 255, 0)));
        txtVeri.setCaretColor(new java.awt.Color(102, 255, 102));
        jScrollPane1.setViewportView(txtVeri);

        btnOku.setText("Oku");
        btnOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkuActionPerformed(evt);
            }
        });

        txtSutunNo.setText("0");

        btnSutunSil.setText("Sutun Sil");
        btnSutunSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSutunSilActionPerformed(evt);
            }
        });

        txtKonsol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtKonsol.setForeground(new java.awt.Color(0, 0, 153));
        jScrollPane2.setViewportView(txtKonsol);

        txtAdayBolunme.setColumns(20);
        txtAdayBolunme.setRows(5);
        jScrollPane3.setViewportView(txtAdayBolunme);

        btnAdayBol.setText("Aday Bolunme");
        btnAdayBol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdayBolActionPerformed(evt);
            }
        });

        btnSolAgac.setText("Sol Ağaç Hesapları");
        btnSolAgac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolAgacActionPerformed(evt);
            }
        });

        btnSagAgac.setText("Sag Agac Hesaplari");
        btnSagAgac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSagAgacActionPerformed(evt);
            }
        });

        txtSolAgac.setColumns(20);
        txtSolAgac.setRows(5);
        jScrollPane4.setViewportView(txtSolAgac);

        txtSagAgac.setColumns(20);
        txtSagAgac.setRows(5);
        jScrollPane5.setViewportView(txtSagAgac);

        txtUygunluk.setColumns(20);
        txtUygunluk.setRows(5);
        jScrollPane6.setViewportView(txtUygunluk);

        btnUygunlukDeger.setText("Uygunluk Degeri");
        btnUygunlukDeger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUygunlukDegerActionPerformed(evt);
            }
        });

        btnBol.setText("Bol");
        btnBol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSolAgac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSagAgac))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOku)
                        .addGap(8, 8, 8)
                        .addComponent(txtSutunNo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSutunSil)
                        .addGap(2, 2, 2)
                        .addComponent(btnAdayBol)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnUygunlukDeger)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBol))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOku)
                    .addComponent(btnSutunSil)
                    .addComponent(txtSutunNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdayBol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSolAgac)
                    .addComponent(btnSagAgac))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUygunlukDeger)
                    .addComponent(btnBol))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkuActionPerformed
        // TODO add your handling code here:
        oku("veri.txt");
    }//GEN-LAST:event_btnOkuActionPerformed

    private void btnSutunSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSutunSilActionPerformed
        // TODO add your handling code here:
        int sutunNo = Integer.parseInt(txtSutunNo.getText());
        String[][] arrTmp = new String[satirSayisi][sutunSayisi - 1];
        println("Satir Sayisi : " + satirSayisi + " , Sutun Sayisi :  " + sutunSayisi);
        int tmpSatir = 0, tmpSutun = 0;
        for (int i = 0; i < satirSayisi; i++) {
            tmpSutun = 0;
            for (int j = 0; j < sutunSayisi; j++) {
                if (j != sutunNo) {
                    arrTmp[i][tmpSutun] = arrVeriler[i][j];
                    tmpSutun++;

                }

            }

        }
        arrVeriler = new String[satirSayisi][sutunSayisi - 1];
        for (int i = 0; i < satirSayisi; i++) {
            for (int j = 0; j < sutunSayisi - 1; j++) {
                arrVeriler[i][j] = arrTmp[i][j];
            }
        }
        sutunSayisi--;
        veriYaz();
    }//GEN-LAST:event_btnSutunSilActionPerformed

    private void btnAdayBolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdayBolActionPerformed
        arrTsag = new ArrayList<>();
        arrTsol = new ArrayList<>();
        ArrayList<String> arrAdayBol = new ArrayList<>();
        String sutunAdi = "";
        for (int i = 0; i < sutunSayisi; i++) {
            // HashSet<String> arrSutunOzellik = new HashSet<>();
            ArrayList<String> arrSutunOzellik = new ArrayList<>();

            // ***Burdaki j=1 ifadesinden dolayi normali almiyor
            for (int j = 1; j < satirSayisi; j++) {
                sutunAdi = arrVeriler[0][i];
                String tmpVeri = sutunAdi + "=" + arrVeriler[j][i];
                if (!arrSutunOzellik.contains(tmpVeri)) {
                    arrSutunOzellik.add(tmpVeri);
                }

            }
            println("\n" + i + ".Ozellik\n");
            for (String string : arrSutunOzellik) {
                print(string + " - ");
                arrTsol.add(string);
            }

            for (int j = 0; j < arrSutunOzellik.size(); j++) {
                String strRaw = arrSutunOzellik.get(j).substring(arrSutunOzellik.get(j).indexOf("=") + 1, arrSutunOzellik.get(j).length());
                println("StrRaw : " + strRaw);
                String strSag = "";
                for (int k = 0; k < arrSutunOzellik.size(); k++) {
                    String tmpRaw = arrSutunOzellik.get(k).substring(arrSutunOzellik.get(k).indexOf("=") + 1, arrSutunOzellik.get(k).length());
                    if (!strRaw.equalsIgnoreCase(tmpRaw)) {
                        strSag += tmpRaw + ",";
                    }
                }
                println("Sag :  " + strSag);
                arrTsag.add(sutunAdi + "=" + strSag);
            }
            println("\n----------------------");
        }
        println("arrSol");
        diziYaz(arrTsol);
        println("arrSag");
        diziYaz(arrTsag);
        String[][] arrAdayBolunme = new String[arrTsag.size() + 1][2];
        arrAdayBolunme[0][0] = "TSol";
        arrAdayBolunme[0][1] = "TSag";
        //ilk veriyi yazmamasinin sebebi burdaki i nin 1 den baslamasiymis
        for (int i = 0; i < arrTsag.size(); i++) {
            arrAdayBolunme[i][0] = arrTsol.get(i);
            arrAdayBolunme[i][1] = arrTsag.get(i);
        }
        int boslukSayisi = 20;
        for (int i = 0; i < arrTsag.size(); i++) {
            for (int j = 0; j < 2; j++) {
                String strBosluk = "";
                for (int k = 0; k < (boslukSayisi - arrAdayBolunme[i][j].length()); k++) {
                    strBosluk += " ";
                }
                txtAdayBolunme.setText(txtAdayBolunme.getText() + arrAdayBolunme[i][j] + strBosluk);
            }
            txtAdayBolunme.setText(txtAdayBolunme.getText() + "\n");
        }

    }//GEN-LAST:event_btnAdayBolActionPerformed
    public void diziYaz(ArrayList<String> arrTmp) {
        println("Dizi : ");
        for (int i = 0; i < arrTmp.size(); i++) {
            println(arrTmp.get(i));
        }
        println("---------- ");
    }
    private void btnSolAgacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolAgacActionPerformed
        // TODO add your handling code here:
        println("Satir Sayisi : " + satirSayisi);
        println("Sutun Sayisi : " + sutunSayisi);

        println("--------------");
        arrTSolHesap = new String[arrTsol.size() + 1][6];
        arrTSolHesap[0][0] = "Kayit Sayisi";
        arrTSolHesap[0][1] = "Psol";
        arrTSolHesap[0][2] = "Evet";
        arrTSolHesap[0][3] = "Hayir";
        arrTSolHesap[0][4] = "P(Evet|Sol)";
        arrTSolHesap[0][5] = "P(Hayir|Sol)";
        double tumKayit = satirSayisi - 1;
        int esitIndex = -1;
        String raw = "", ozellik = "", deger = "";
        String strEvet, strHayir = "";
        strEvet = arrNitelik.get(1);
        for (int i = 2; i < arrNitelik.size(); i++) {
            if (!strEvet.equalsIgnoreCase(arrNitelik.get(i))) {
                strHayir = arrNitelik.get(i);
            }
        }
        println("StrEVet : " + strEvet);
        println("strHayir : " + strHayir);
        //burasi karisacak,pozisyon alin
        for (int i = 0; i < arrTsol.size(); i++) {
            raw = arrTsol.get(i);
            println("Raw : " + raw);
            esitIndex = raw.indexOf("=");
            ozellik = raw.substring(0, esitIndex);
            println("Ozellik : " + ozellik);
            deger = raw.substring(esitIndex + 1, raw.length());
            println("Deger : " + deger);
            int ozellikIndex = -1;
            for (int j = 0; j < sutunSayisi; j++) {
                if (arrVeriler[0][j].equalsIgnoreCase(ozellik)) {
                    ozellikIndex = j;
                    println("Ozellik Index : " + ozellikIndex);
                    break;
                }
            }
            double sayac = 0;
            for (int j = 0; j < satirSayisi; j++) {
                if (arrVeriler[j][ozellikIndex].equalsIgnoreCase(deger)) {
                    sayac++;
                }
            }
            println(deger + " Sayisi : " + sayac);
            arrTSolHesap[i + 1][0] = sayac + "";
            double Psol = sayac / tumKayit;
            String tmpStr = Psol + "";
            if (tmpStr.length() > 5) {
                tmpStr = tmpStr.substring(0, 5);
            }
            arrTSolHesap[i + 1][1] = tmpStr;
            double evetSayac = 0, hayirSayac = 0;
            //Evet Hayir sayilari
            for (int j = 1; j < satirSayisi; j++) {
                println("Deger : " + arrVeriler[j][ozellikIndex]);
                if (arrVeriler[j][ozellikIndex].equals(deger)) {
                    if (arrNitelik.get(j).equalsIgnoreCase(strEvet)) {
                        evetSayac++;
                    } else if (arrNitelik.get(j).equalsIgnoreCase(strHayir)) {
                        hayirSayac++;
                    }
                }
            }
            arrTSolHesap[i + 1][2] = evetSayac + "";
            arrTSolHesap[i + 1][3] = hayirSayac + "";

            NumberFormat nf = new DecimalFormat("#0.00");
            String strSonuc = "";
            double sonuc;
            sonuc = evetSayac / (evetSayac + hayirSayac);
            strSonuc = nf.format(sonuc);
            arrTSolHesap[i + 1][4] = strSonuc;

            sonuc = hayirSayac / (evetSayac + hayirSayac);
            strSonuc = nf.format(sonuc);
            arrTSolHesap[i + 1][5] = strSonuc;
            println("--------------");
        }

        //burasi txt ye yazma kismi,asil kisim yukarda
        int[] arrAlan = {25, 10, 10, 15, 30, 20};
        int boslukSayisi = 15;
        for (int i = 0; i < arrTsol.size() + 1; i++) {
            for (int j = 0; j < 6; j++) {
                String strBosluk = "";
                boslukSayisi = (arrAlan[j] - (arrTSolHesap[i][j] + "").length());
                for (int k = 0; k < boslukSayisi; k++) {
                    if (i == 0 && j == 0) {
                        boslukSayisi = +5;
                        strBosluk += " ";
                    } else {

                        strBosluk += " ";
                    }

                }

                txtSolAgac.setText(txtSolAgac.getText() + arrTSolHesap[i][j] + strBosluk);
            }
            txtSolAgac.setText(txtSolAgac.getText() + "\n");
        }
    }//GEN-LAST:event_btnSolAgacActionPerformed

    private void btnSagAgacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSagAgacActionPerformed
        // TODO add your handling code here:
        println("Satir Sayisi : " + satirSayisi);
        println("Sutun Sayisi : " + sutunSayisi);

        println("--------------");
        arrTSagHesap = new String[arrTsag.size() + 1][6];
        arrTSagHesap[0][0] = "Kayit Sayisi";
        arrTSagHesap[0][1] = "Psag";
        arrTSagHesap[0][2] = "Evet";
        arrTSagHesap[0][3] = "Hayir";
        arrTSagHesap[0][4] = "P(Evet|Sag)";
        arrTSagHesap[0][5] = "P(Hayir|Sag)";
        double tumKayit = satirSayisi - 1;
        int esitIndex = -1;
        String raw = "", ozellik = "", deger = "";

        String strEvet, strHayir = "";
        strEvet = arrNitelik.get(1);
        for (int i = 2; i < arrNitelik.size(); i++) {
            if (!strEvet.equalsIgnoreCase(arrNitelik.get(i))) {
                strHayir = arrNitelik.get(i);
            }
        }
        println("StrEVet : " + strEvet);
        println("strHayir : " + strHayir);
        //burasi karisacak,pozisyon alin
        for (int i = 0; i < arrTsag.size(); i++) {
            raw = arrTsag.get(i);
            println("Raw : " + raw);
            esitIndex = raw.indexOf("=");
            ozellik = raw.substring(0, esitIndex);
            println("Ozellik : " + ozellik);
            deger = raw.substring(esitIndex + 1, raw.length());
            println("Deger : " + deger);
            String[] arrDeger = deger.split(",");
            int ozellikIndex = -1;
            for (int j = 0; j < sutunSayisi; j++) {
                if (arrVeriler[0][j].equalsIgnoreCase(ozellik)) {
                    ozellikIndex = j;
                    println("Ozellik Index : " + ozellikIndex);
                    break;
                }
            }
            double sayac = 0;
            for (int j = 0; j < satirSayisi; j++) {
                for (int k = 0; k < arrDeger.length; k++) {
                    if (arrVeriler[j][ozellikIndex].equalsIgnoreCase(arrDeger[k])) {
                        sayac++;
                    }
                }

            }
            println(deger + " Sayisi : " + sayac);
            arrTSagHesap[i + 1][0] = sayac + "";
            double Psol = sayac / tumKayit;
            String tmpStr = Psol + "";
            if (tmpStr.length() > 5) {
                tmpStr = tmpStr.substring(0, 5);
            }
            arrTSagHesap[i + 1][1] = tmpStr;
            double evetSayac = 0, hayirSayac = 0;
            //Evet Hayir sayilari
            for (int j = 1; j < satirSayisi; j++) {
                println("Deger : " + arrVeriler[j][ozellikIndex]);
                boolean isFind = false;
                for (int k = 0; k < arrDeger.length; k++) {
                    if (arrVeriler[j][ozellikIndex].equals(arrDeger[k])) {
                        isFind = true;
                        break;
                    }
                }
                if (isFind) {

                    if (arrNitelik.get(j).equalsIgnoreCase(strEvet)) {
                        evetSayac++;
                    } else if (arrNitelik.get(j).equalsIgnoreCase(strHayir)) {
                        hayirSayac++;
                    }
                }
            }
            arrTSagHesap[i + 1][2] = evetSayac + "";
            arrTSagHesap[i + 1][3] = hayirSayac + "";

            NumberFormat nf = new DecimalFormat("#0.00");
            String strSonuc = "";
            double sonuc;
            sonuc = evetSayac / (evetSayac + hayirSayac);
            strSonuc = nf.format(sonuc);
            arrTSagHesap[i + 1][4] = strSonuc;

            sonuc = hayirSayac / (evetSayac + hayirSayac);
            strSonuc = nf.format(sonuc);
            arrTSagHesap[i + 1][5] = strSonuc;
            println("--------------");
        }

        //burasi txt ye yazma kismi,asil kisim yukarda
        int[] arrAlan = {25, 10, 10, 15, 30, 20};
        int boslukSayisi = 15;
        for (int i = 0; i < arrTsol.size() + 1; i++) {
            for (int j = 0; j < 6; j++) {
                String strBosluk = "";
                boslukSayisi = (arrAlan[j] - (arrTSagHesap[i][j] + "").length());
                for (int k = 0; k < boslukSayisi; k++) {
                    if (i == 0 && j == 0) {
                        boslukSayisi = +5;
                        strBosluk += " ";
                    } else {

                        strBosluk += " ";
                    }

                }

                txtSagAgac.setText(txtSagAgac.getText() + arrTSagHesap[i][j] + strBosluk);
            }
            txtSagAgac.setText(txtSagAgac.getText() + "\n");
        }
    }//GEN-LAST:event_btnSagAgacActionPerformed
    static int tmpBolIndex;
    private void btnUygunlukDegerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUygunlukDegerActionPerformed
        // TODO add your handling code here:
        diziYaz(arrTSolHesap);
        diziYaz(arrTSagHesap);
        double PsolPsag;
        double PEvetFark;
        double PHayirFark;
        double uygunlukDegeri;
        println("arrTSagHesap[0].length : " + arrTSagHesap[0].length);
        println("arrTSagHesap[1].length : " + arrTSagHesap[1].length);
        txtUygunluk.setText("Uygunluk Değerleri\n");
        for (int i = 1; i < arrTsag.size() + 1; i++) {
            PsolPsag = (conD(arrTSagHesap[i][1])) * conD(arrTSolHesap[i][1]);

            PEvetFark = (conD(arrTSolHesap[i][4])) - conD(arrTSagHesap[i][4]);
            PEvetFark = Math.abs(PEvetFark);

            PHayirFark = (conD(arrTSolHesap[i][5])) - conD(arrTSagHesap[i][5]);
            PHayirFark = Math.abs(PHayirFark);
            uygunlukDegeri = 2 * PsolPsag * (PHayirFark + PEvetFark);
            println("uygunlukDegeri : " + uygunlukDegeri);
            arrUygunlukDegeri.add(uygunlukDegeri);
            txtUygunluk.setText(txtUygunluk.getText() + uygunlukDegeri + "\n");
        }
        int enBuyukIndex = 0;

        for (int i = 1; i < arrUygunlukDegeri.size(); i++) {
            if (arrUygunlukDegeri.get(i) > arrUygunlukDegeri.get(enBuyukIndex)) {
                enBuyukIndex = i;
            }
        }
        println("----------------------------");
        println("En Buyuk İndex :  " + enBuyukIndex);
        println("En Buyuk İndexteki Deger :  " + arrUygunlukDegeri.get(enBuyukIndex));
        println("En Buyuk İndexteki Aday : " + arrTsol.get(enBuyukIndex));
        int esitIndex = arrTsol.get(enBuyukIndex).indexOf("=");
        String nitelik = arrTsol.get(enBuyukIndex).substring(0, esitIndex);
        println("Nitelik : " + nitelik);
        String ozellik = arrTsol.get(enBuyukIndex).substring(esitIndex + 1, arrTsol.get(enBuyukIndex).length());
        println("Ozellik : " + ozellik);

        for (int i = 0; i < sutunSayisi; i++) {
            if (arrVeriler[0][i].equalsIgnoreCase(nitelik)) {
                tmpBolIndex = i;
                break;
            }
        }
        println("tmpBolIndex : " + tmpBolIndex);

    }//GEN-LAST:event_btnUygunlukDegerActionPerformed

    private void btnBolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBolActionPerformed
        // TODO add your handling code here:

        for (int j = 1; j < satirSayisi; j++) {
            print(arrVeriler[j][tmpBolIndex] + "      ");
        }

//        int satir
//        int bolSatirIndex = 0;

    }//GEN-LAST:event_btnBolActionPerformed
    public double conD(String strDouble) {
        strDouble = strDouble.replaceAll(",", ".");
        return Double.parseDouble(strDouble);
    }

    /**
     * @param args the command line arguments
     */
    public void oku(String strPath) {
        BufferedReader br = null;
        FileReader fr = null;
        String strTmp = "";
        try {
            fr = new FileReader(strPath);
            br = new BufferedReader(fr);

            while ((strTmp = br.readLine()) != null) {
                satirSayisi++;
                if (satirSayisi == 1) {
                    sutunSayisi = strTmp.split(",").length;
                    println("Sutun Sayisi : " + sutunSayisi);
                }
            }
            println("Satir Sayisi : " + satirSayisi);
        } catch (Exception ex) {
            hata(ex);
        } finally {
            try {
                br.close();
                fr.close();
            } catch (IOException ex) {
                hata(ex);
            }
        }

        //Satir ve Sutun Sayisini aldiktan sonra bir matrise yerlestirelim
        try {
            println("Veriler Yerlestiriliyor..");
            arrVeriler = new String[satirSayisi][sutunSayisi];
            fr = new FileReader(strPath);
            br = new BufferedReader(fr);
            strTmp = "";
            int satir = 0;
            while ((strTmp = br.readLine()) != null) {

                String[] arrTmp = strTmp.split(",");
                for (int sutun = 0; sutun < arrTmp.length; sutun++) {
                    arrVeriler[satir][sutun] = arrTmp[sutun];
                }
                satir++;
            }
            veriYaz();
        } catch (Exception e) {
            hata(e);

        }
        //nitelik sutunu
        arrNitelik = new ArrayList<>();
        String tmpNitelik = "";
        println("--------------");
        for (int i = 0; i < satirSayisi; i++) {
            tmpNitelik = arrVeriler[i][sutunSayisi - 1];
            arrNitelik.add(tmpNitelik);
            println(tmpNitelik);
        }
//nitelik sutunu bir gider misin?
        int sutunNo = sutunSayisi - 1;
        String[][] arrTmp = new String[satirSayisi][sutunSayisi - 1];
        println("Satir Sayisi : " + satirSayisi + " , Sutun Sayisi :  " + sutunSayisi);
        int tmpSatir = 0, tmpSutun = 0;
        for (int i = 0; i < satirSayisi; i++) {
            tmpSutun = 0;
            for (int j = 0; j < sutunSayisi; j++) {
                if (j != sutunNo) {
                    arrTmp[i][tmpSutun] = arrVeriler[i][j];
                    tmpSutun++;

                }

            }
        }
        arrVeriler = new String[satirSayisi][sutunSayisi - 1];
        for (int i = 0; i < satirSayisi; i++) {
            for (int j = 0; j < sutunSayisi - 1; j++) {
                arrVeriler[i][j] = arrTmp[i][j];
            }
        }
        sutunSayisi--;

    }

    public void veriYaz() {
        txtVeri.setText("");
        int[] arrAlan = {15, 15, 15, 15, 15};
        int boslukSayisi = 15;
        for (int i = 0; i < satirSayisi; i++) {
            for (int j = 0; j < sutunSayisi; j++) {
                println("---------------");
                println(arrVeriler[i][j]);

                //bosluk hesapla
                String bosluk = "";
                boslukSayisi = (15 - arrVeriler[i][j].length());
                // println("bosluk sayisi : " + boslukSayisi);
                for (int k = 0; k < boslukSayisi; k++) {
                    bosluk += " ";
                }
                println("bosluk sayisi : " + boslukSayisi);
                println("---------------");
                txtVeri.setText(txtVeri.getText() + arrVeriler[i][j] + bosluk);

            }
            txtVeri.setText(txtVeri.getText() + "\n");
        }
    }

    public void print(String strLog) {
        txtKonsol.setText(txtKonsol.getText() + strLog);
    }

    public void println(String strLog) {
        txtKonsol.setText(txtKonsol.getText() + strLog + "\n");
    }

    public void hata(Exception ex) {
        println("Hata : " + ex.getMessage() + ex.getCause());
        println("Satir : " + ex.getStackTrace()[0].getLineNumber());
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAnaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdayBol;
    private javax.swing.JButton btnBol;
    private javax.swing.JButton btnOku;
    private javax.swing.JButton btnSagAgac;
    private javax.swing.JButton btnSolAgac;
    private javax.swing.JButton btnSutunSil;
    private javax.swing.JButton btnUygunlukDeger;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea txtAdayBolunme;
    private javax.swing.JTextPane txtKonsol;
    private javax.swing.JTextArea txtSagAgac;
    private javax.swing.JTextArea txtSolAgac;
    private javax.swing.JTextField txtSutunNo;
    private javax.swing.JTextArea txtUygunluk;
    private javax.swing.JTextArea txtVeri;
    // End of variables declaration//GEN-END:variables

    private void diziYaz(String[][] arrTmp) {
        println("Dizi : ");
        for (int i = 0; i < arrTmp[0].length; i++) {
            for (int j = 0; j < arrTmp[1].length; j++) {
                print(arrTmp[i][j] + "      ");
            }

        }
        println("---------- ");
    }
}
